// AUTO-GENERATED by scripts/generate-catalog.mjs — do not edit by hand.
import type { Category, Product } from './types'

export const categories: Category[] = [
  {
    "id": 29,
    "slug": "ensemble-de-logiciels",
    "nameFr": "ENSEMBLE DE LOGICIELS",
    "nameAr": "مجموعة من البرمجيات خاصة بالمؤسسات التربوية",
    "count": 5,
    "image": "/images/cat-01.jpg"
  },
  {
    "id": 37,
    "slug": "mobilier-de-laboratoire-et-de-bureau",
    "nameFr": "MOBILIER DE LABORATOIRE ET DE BUREAU",
    "nameAr": "أثاث المخابر و المكاتب",
    "count": 61,
    "image": "/images/cat-02.jpg"
  },
  {
    "id": 28,
    "slug": "education-physique-et-sportive",
    "nameFr": "EDUCATION PHYSIQUE ET SPORTIVE",
    "nameAr": "لوازم التربية البدنية",
    "count": 83,
    "image": "/images/cat-03.jpg"
  },
  {
    "id": 38,
    "slug": "tp-physique-et-chimie",
    "nameFr": "TP PHYSIQUE ET CHIMIE",
    "nameAr": "مجموعة لدراسة الفيزياء و الكيمياء",
    "count": 447,
    "image": "/images/cat-04.jpg"
  },
  {
    "id": 27,
    "slug": "geologie",
    "nameFr": "GEOLOGIE",
    "nameAr": "مجموعة لدراسة الجيولوجيا",
    "count": 40,
    "image": "/images/cat-05.jpg"
  },
  {
    "id": 25,
    "slug": "science-de-la-vie-et-de-la-terre",
    "nameFr": "SCIENCE DE LA VIE ET DE LA TERRE",
    "nameAr": "مجموعة لدراسة العلوم الطبيعية و الحياة",
    "count": 215,
    "image": "/images/cat-06.jpg"
  },
  {
    "id": 22,
    "slug": "materiels-dobservation",
    "nameFr": "MATERIELS D’OBSERVATION",
    "nameAr": "المجاهر",
    "count": 22,
    "image": "/images/cat-07.jpg"
  },
  {
    "id": 23,
    "slug": "verrerie-de-laboratoire",
    "nameFr": "VERRERIE DE LABORATOIRE",
    "nameAr": "أدوات زجاجية للمخابر",
    "count": 269,
    "image": "/images/cat-08.jpg"
  },
  {
    "id": 24,
    "slug": "audio-visuel-et-animation-culturelle",
    "nameFr": "AUDIO-VISUAL & ANIMATION CULTURELLE",
    "nameAr": "الأجهزة السمعية البصرية & النشاط الثقافي",
    "count": 142,
    "image": "/images/cat-09.jpg"
  },
  {
    "id": 20,
    "slug": "cartes-geographiques",
    "nameFr": "GEOGRAPHIQUES CARTES",
    "nameAr": "دليل الخرائط الجغرافية التاريخية",
    "count": 372,
    "image": "/images/cat-10.jpg"
  },
  {
    "id": 19,
    "slug": "produits-chimiques",
    "nameFr": "CHIMIQUES PRODUITS",
    "nameAr": "مجموعة من المواد الكيميائية",
    "count": 176,
    "image": "/images/cat-11.jpg"
  },
  {
    "id": 18,
    "slug": "arduino-et-electronique",
    "nameFr": "ARDUINO & ELECTRONIQUE",
    "nameAr": "أردوينو & الإلكترونیك",
    "count": 94,
    "image": "/images/cat-12.jpg"
  }
]

export const products: Product[] = [
  {
    "id": 783,
    "slug": "logiciel-el-djerd",
    "ref": "L001",
    "nameFr": "Logiciel EL DJERD",
    "nameAr": "الجرد",
    "price": 5850,
    "categorySlug": "ensemble-de-logiciels",
    "image": "/images/products/LOG-05-1.jpg"
  },
  {
    "id": 786,
    "slug": "logiciel-la-caisse",
    "ref": "L002",
    "nameFr": "Logiciel LA CAISSE",
    "nameAr": "لاكيس",
    "price": 8190,
    "categorySlug": "ensemble-de-logiciels",
    "image": "/images/products/LOG-02.jpg"
  },
  {
    "id": 798,
    "slug": "logiciel-nutrisco",
    "ref": "L003",
    "nameFr": "Logiciel NUTRISCO",
    "nameAr": "نوتريسكو",
    "price": 5850,
    "categorySlug": "ensemble-de-logiciels",
    "image": "/images/products/LOG-04.jpg"
  },
  {
    "id": 780,
    "slug": "logiciel-planisco",
    "ref": "L004",
    "nameFr": "Logiciel PLANISCO",
    "nameAr": "بلانيسكو",
    "price": 5850,
    "categorySlug": "ensemble-de-logiciels",
    "image": "/images/products/LOG-03-1.jpg"
  },
  {
    "id": 773,
    "slug": "logiciel-wgesco",
    "ref": "L005",
    "nameFr": "Logiciel WGESCO",
    "nameAr": "وين جيسكو",
    "price": 8190,
    "categorySlug": "ensemble-de-logiciels",
    "image": "/images/products/LOG-01-1.jpg"
  },
  {
    "id": 1060,
    "slug": "armoire-a-10-portes-10",
    "ref": "F001",
    "nameFr": "Armoire à 10 portes",
    "nameAr": "خزانة بـ 10 أبواب",
    "price": 42000,
    "categorySlug": "mobilier-de-laboratoire-et-de-bureau",
    "image": "/images/products/BI48-2.jpg"
  },
  {
    "id": 1069,
    "slug": "armoire-a-12-portes-12",
    "ref": "F002",
    "nameFr": "Armoire à 12 portes",
    "nameAr": "خزانة بـ 12 أبواب",
    "price": 43000,
    "categorySlug": "mobilier-de-laboratoire-et-de-bureau",
    "image": "/images/products/BI49.PPP_-2.jpg"
  },
  {
    "id": 1024,
    "slug": "armoire-a-5-portes-5",
    "ref": "F003",
    "nameFr": "Armoire à 5 portes",
    "nameAr": "خزانة بـ 5 أبواب",
    "price": 28000,
    "categorySlug": "mobilier-de-laboratoire-et-de-bureau",
    "image": "/images/products/DO00690-Casier-vestaiare-metallique-03-2.jpg"
  },
  {
    "id": 1120,
    "slug": "armoire-a-cle-120-cle-120",
    "ref": "F004",
    "nameFr": "Armoire à clé (120 clé)",
    "nameAr": "خزانة للمفاتيح (120 مفتاح)",
    "price": 12500,
    "categorySlug": "mobilier-de-laboratoire-et-de-bureau",
    "image": "/images/products/BI17.jpg"
  },
  {
    "id": 1103,
    "slug": "armoire-a-cle-24-cle-24",
    "ref": "F005",
    "nameFr": "Armoire à clé (24 clé)",
    "nameAr": "خزانة للمفاتيح (24 مفتاح)",
    "price": 3900,
    "categorySlug": "mobilier-de-laboratoire-et-de-bureau",
    "image": "/images/products/BI17.jpg"
  },
  {
    "id": 1106,
    "slug": "armoire-a-cle-32-cle-32",
    "ref": "F006",
    "nameFr": "Armoire à clé (32 clé)",
    "nameAr": "خزانة للمفاتيح (32 مفتاح)",
    "price": 4800,
    "categorySlug": "mobilier-de-laboratoire-et-de-bureau",
    "image": "/images/products/BI17.jpg"
  },
  {
    "id": 1108,
    "slug": "armoire-a-cle-48-cle-48",
    "ref": "F007",
    "nameFr": "Armoire à clé (48 clé)",
    "nameAr": "خزانة للمفاتيح (48 مفتاح)",
    "price": 6450,
    "categorySlug": "mobilier-de-laboratoire-et-de-bureau",
    "image": "/images/products/BI17.jpg"
  },
  {
    "id": 1117,
    "slug": "armoire-a-cle-72-cle-72",
    "ref": "F008",
    "nameFr": "Armoire à clé (72 clé)",
    "nameAr": "خزانة للمفاتيح (72 مفتاح)",
    "price": 8000,
    "categorySlug": "mobilier-de-laboratoire-et-de-bureau",
    "image": "/images/products/BI17.jpg"
  },
  {
    "id": 1119,
    "slug": "armoire-a-cle-96-cle-96",
    "ref": "F009",
    "nameFr": "Armoire à clé (96 clé)",
    "nameAr": "خزانة للمفاتيح (96 مفتاح)",
    "price": 12000,
    "categorySlug": "mobilier-de-laboratoire-et-de-bureau",
    "image": "/images/products/BI17.jpg"
  },
  {
    "id": 970,
    "slug": "armoire-bibliotheque",
    "ref": "F010",
    "nameFr": "Armoire bibliothèque",
    "nameAr": "خزانة للمكتبة",
    "price": 36000,
    "categorySlug": "mobilier-de-laboratoire-et-de-bureau",
    "image": "/images/products/GLT0602-2-1.jpg"
  },
  {
    "id": 959,
    "slug": "armoire-forte-avec-combinaison",
    "ref": "F011",
    "nameFr": "Armoire forte avec combinaison",
    "nameAr": "خزانة حديدية مدرعة بأرقام سرية",
    "price": 61000,
    "categorySlug": "mobilier-de-laboratoire-et-de-bureau",
    "image": "/images/products/BI31-1.jpg"
  },
  {
    "id": 967,
    "slug": "armoire-forte-avec-combinaison-digitale",
    "ref": "F012",
    "nameFr": "Armoire forte avec combinaison digitale",
    "nameAr": "خزانة حديدية مدرعة بأرقام سرية و شاشة رقمية",
    "price": 62500,
    "categorySlug": "mobilier-de-laboratoire-et-de-bureau",
    "image": "/images/products/BI31-2.jpg"
  },
  {
    "id": 964,
    "slug": "armoire-forte-sans-combinaison",
    "ref": "F013",
    "nameFr": "Armoire forte sans combinaison",
    "nameAr": "خزانة حديدية مدرعة بدون أرقام سرية",
    "price": 52500,
    "categorySlug": "mobilier-de-laboratoire-et-de-bureau",
    "image": "/images/products/BI31-2.jpg"
  },
  {
    "id": 955,
    "slug": "armoire-metallique",
    "ref": "F014",
    "nameFr": "Armoire métallique",
    "nameAr": "خزانة حديدية",
    "price": 32000,
    "categorySlug": "mobilier-de-laboratoire-et-de-bureau",
    "image": "/images/products/bi05.jpg"
  },
  {
    "id": 989,
    "slug": "armoire-vitre-pour-laboratoire",
    "ref": "F015",
    "nameFr": "Armoire vitré pour laboratoire",
    "nameAr": "خزانة زجاجية للمخبر",
    "price": 34500,
    "categorySlug": "mobilier-de-laboratoire-et-de-bureau",
    "image": "/images/products/bi07.jpg"
  },
  {
    "id": 2034,
    "slug": "balles-de-ping-pong-lot-de-03",
    "ref": "S001",
    "nameFr": "Balles de ping-pong Lot de 03",
    "nameAr": "كريات طاولة التنس",
    "price": 1400,
    "categorySlug": "education-physique-et-sportive",
    "image": "/images/products/images-12-scaled.jpg"
  },
  {
    "id": 1378,
    "slug": "balles-leesteees-1kg-1",
    "ref": "S002",
    "nameFr": "Balles lestées 1Kg",
    "nameAr": "جلات مطاطية 1 كغ",
    "price": 1950,
    "categorySlug": "education-physique-et-sportive",
    "image": "/images/products/picture.jpg"
  },
  {
    "id": 1586,
    "slug": "balles-lestees-2kg-2",
    "ref": "S003",
    "nameFr": "Balles lestées 2Kg",
    "nameAr": "جلات مطاطية 2 كغ",
    "price": 2400,
    "categorySlug": "education-physique-et-sportive",
    "image": "/images/products/picture.jpg"
  },
  {
    "id": 1279,
    "slug": "ballon-de-basket-ball-dentrainement",
    "ref": "S004",
    "nameFr": "Ballon de basket-ball d’entrainement",
    "nameAr": "كرة السلة للتدريب",
    "price": 1450,
    "categorySlug": "education-physique-et-sportive",
    "image": "/images/products/S05.jpg"
  },
  {
    "id": 1282,
    "slug": "ballon-de-basket-ball-de-competition",
    "ref": "S005",
    "nameFr": "Ballon de basket-ball de compétition",
    "nameAr": "كرة السلة للمنافسة",
    "price": 4500,
    "categorySlug": "education-physique-et-sportive",
    "image": "/images/products/S05.jpg"
  },
  {
    "id": 1273,
    "slug": "ballon-de-foot-ball-dentrainement",
    "ref": "S006",
    "nameFr": "Ballon de foot-ball d’entrainement",
    "nameAr": "كرة القدم للتدريب",
    "price": 2500,
    "categorySlug": "education-physique-et-sportive",
    "image": "/images/products/S01-1.jpg"
  },
  {
    "id": 1276,
    "slug": "ballon-de-foot-ball-de-competition",
    "ref": "S007",
    "nameFr": "Ballon de foot-ball de compétition",
    "nameAr": "كرة القدم للمنافسة",
    "price": 4950,
    "categorySlug": "education-physique-et-sportive",
    "image": "/images/products/S01-1.jpg"
  },
  {
    "id": 1277,
    "slug": "ballon-de-hand-ball-dentrainement-n-0-0",
    "ref": "S008",
    "nameFr": "Ballon de hand-ball d’entrainement N° 0",
    "nameAr": "كرة اليد للتدريب رقم 0",
    "price": 1750,
    "categorySlug": "education-physique-et-sportive",
    "image": "/images/products/S03.jpg"
  },
  {
    "id": 1293,
    "slug": "ballon-de-hand-ball-dentrainement-n1-1",
    "ref": "S009",
    "nameFr": "Ballon de hand-ball d’entrainement n°1",
    "nameAr": "كرة اليد للتدريب رقم 1",
    "price": 1750,
    "categorySlug": "education-physique-et-sportive",
    "image": "/images/products/S03.jpg"
  },
  {
    "id": 1295,
    "slug": "ballon-de-hand-ball-dentrainement-n2-2",
    "ref": "S010",
    "nameFr": "Ballon de hand-ball d’entrainement n°2",
    "nameAr": "كرة اليد للتدريب رقم 2",
    "price": 1750,
    "categorySlug": "education-physique-et-sportive",
    "image": "/images/products/S03.jpg"
  },
  {
    "id": 1300,
    "slug": "ballon-de-hand-ball-dentrainement-n3-3",
    "ref": "S011",
    "nameFr": "Ballon de hand-ball d’entrainement n°3",
    "nameAr": "كرة اليد للتدريب رقم 3",
    "price": 1750,
    "categorySlug": "education-physique-et-sportive",
    "image": "/images/products/S03.jpg"
  },
  {
    "id": 1306,
    "slug": "ballon-de-hand-ball-de-competition-n-0-0",
    "ref": "S012",
    "nameFr": "Ballon de hand-ball de compétition N° 0",
    "nameAr": "كرة اليد للمنافسة رقم 0",
    "price": 3200,
    "categorySlug": "education-physique-et-sportive",
    "image": "/images/products/S03.jpg"
  },
  {
    "id": 1310,
    "slug": "ballon-de-hand-ball-de-competition-n-1-1",
    "ref": "S013",
    "nameFr": "Ballon de hand-ball de compétition N° 1",
    "nameAr": "كرة اليد للمنافسة رقم 1",
    "price": 3200,
    "categorySlug": "education-physique-et-sportive",
    "image": "/images/products/S03.jpg"
  },
  {
    "id": 1319,
    "slug": "ballon-de-hand-ball-de-competition-n-2-2",
    "ref": "S014",
    "nameFr": "Ballon de hand-ball de compétition N° 2",
    "nameAr": "كرة اليد للمنافسة رقم 2",
    "price": 3200,
    "categorySlug": "education-physique-et-sportive",
    "image": "/images/products/S03.jpg"
  },
  {
    "id": 1321,
    "slug": "ballon-de-hand-ball-de-competition-n-3-3",
    "ref": "S015",
    "nameFr": "Ballon de hand-ball de compétition N° 3",
    "nameAr": "كرة اليد للمنافسة رقم 3",
    "price": 3200,
    "categorySlug": "education-physique-et-sportive",
    "image": "/images/products/S03.jpg"
  },
  {
    "id": 4028,
    "slug": "ensemble-pour-letude-des-phenomenes-mecaniques-4-am-2",
    "ref": "T001",
    "nameFr": "Actions réciproques entre deux systèmes mécaniques",
    "nameAr": "الأفعال المتبادلة بين جملتين ميكانيكيتين",
    "price": 5800,
    "categorySlug": "tp-physique-et-chimie",
    "image": "/images/products/Untitled-12.jpg"
  },
  {
    "id": 3191,
    "slug": "agitateur-magnetique",
    "ref": "T002",
    "nameFr": "Agitateur magnétique Chauffant",
    "nameAr": "جهاز مخلط كهرومغناطيسي",
    "price": 30000,
    "categorySlug": "tp-physique-et-chimie",
    "image": "/images/products/p836.jpg"
  },
  {
    "id": 3193,
    "slug": "agitateur-magnetique-non-chauffant",
    "ref": "T003",
    "nameFr": "Agitateur magnétique Non Chauffant",
    "nameAr": "جهاز مخلط كهرومغناطيسي",
    "price": 13000,
    "categorySlug": "tp-physique-et-chimie",
    "image": "/images/products/p792.jpg"
  },
  {
    "id": 3197,
    "slug": "agitateur-magnetique-non-chauffant-2",
    "ref": "T004",
    "nameFr": "Agitateur magnétique Non Chauffant",
    "nameAr": "جهاز مخلط كهرومغناطيسي",
    "price": 9500,
    "categorySlug": "tp-physique-et-chimie",
    "image": "/images/products/p856.jpg"
  },
  {
    "id": 3238,
    "slug": "aiguille-aimantee-sur-socle",
    "ref": "T005",
    "nameFr": "Aiguille aimantée sur socle",
    "nameAr": "إبرة ممغنطة على حامل",
    "price": 500,
    "categorySlug": "tp-physique-et-chimie",
    "image": "/images/products/p146.jpg"
  },
  {
    "id": 3236,
    "slug": "aiguille-dorsted",
    "ref": "T006",
    "nameFr": "Aiguille d’ORSTED",
    "nameAr": "إبرة أرستد",
    "price": 2950,
    "categorySlug": "tp-physique-et-chimie",
    "image": "/images/products/p137.jpg"
  },
  {
    "id": 3210,
    "slug": "aimant-annulaire",
    "ref": "T007",
    "nameFr": "Aimant annulaire",
    "nameAr": "مغناطيس حلقي",
    "price": 1200,
    "categorySlug": "tp-physique-et-chimie",
    "image": "/images/products/p880.jpg"
  },
  {
    "id": 3221,
    "slug": "aimant-en-fer-a-cheval",
    "ref": "T008",
    "nameFr": "Aimant en fer à cheval",
    "nameAr": "مغناطيس على شكل حدوة حصان",
    "price": 3000,
    "categorySlug": "tp-physique-et-chimie",
    "image": "/images/products/p047.jpg"
  },
  {
    "id": 3223,
    "slug": "aimant-en-forme-de-u-modele-01",
    "ref": "T009",
    "nameFr": "Aimant en forme de U Modèle 01",
    "nameAr": "مغناطيس على شكل حرف",
    "price": 3950,
    "categorySlug": "tp-physique-et-chimie",
    "image": "/images/products/p163.jpg"
  },
  {
    "id": 3227,
    "slug": "aimant-en-forme-de-u-modele-02",
    "ref": "T010",
    "nameFr": "Aimant en forme de U Modèle 02",
    "nameAr": "مغناطيس على شكل حرف",
    "price": 1950,
    "categorySlug": "tp-physique-et-chimie",
    "image": "/images/products/p163.jpg"
  },
  {
    "id": 2978,
    "slug": "alimentation-numerique",
    "ref": "T011",
    "nameFr": "Alimentation numérique",
    "nameAr": "مغذية رقمية",
    "price": 25000,
    "categorySlug": "tp-physique-et-chimie",
    "image": "/images/products/Untitled-22.jpg"
  },
  {
    "id": 3007,
    "slug": "alimentation-numerique-a-basse-tension",
    "ref": "T012",
    "nameFr": "Alimentation numérique à basse tension",
    "nameAr": "مغذية رقمية بتوتر منخفض",
    "price": 37500,
    "categorySlug": "tp-physique-et-chimie",
    "image": "/images/products/P845.jpg"
  },
  {
    "id": 4238,
    "slug": "alimentation-regulee-v5",
    "ref": "T013",
    "nameFr": "Alimentation régulée V5",
    "nameAr": "تغذية منتظمة",
    "price": 4950,
    "categorySlug": "tp-physique-et-chimie",
    "image": "/images/products/P284F.jpg"
  },
  {
    "id": 4247,
    "slug": "alimentation-regulee-pedagogique",
    "ref": "T014",
    "nameFr": "Alimentation régulée pédagogique",
    "nameAr": "تغذية منتظمة مفككة",
    "price": 4950,
    "categorySlug": "tp-physique-et-chimie",
    "image": "/images/products/P285.jpg"
  },
  {
    "id": 3902,
    "slug": "allumage-dune-lampe-par-leffet-de-la-chute-deau-sur-une-turbine",
    "ref": "T015",
    "nameFr": "Allumage d’une lampe par l’effet de la chute d’eau sur une turbine",
    "nameAr": "اشعال مصباح بسقوط الماء على عنفة",
    "price": 16500,
    "categorySlug": "tp-physique-et-chimie",
    "image": "/images/products/P303.jpg"
  },
  {
    "id": 854,
    "slug": "boite-de-mineraux-colores",
    "ref": "G001",
    "nameFr": "Boite de minéraux colorés",
    "nameAr": "مجموعة معادن ملونة",
    "price": 7000,
    "categorySlug": "geologie",
    "image": "/images/products/m241.jpg"
  },
  {
    "id": 858,
    "slug": "boite-de-roches-mutantes",
    "ref": "G002",
    "nameFr": "Boite de roches mutantes",
    "nameAr": "مجموعة صخور متحولة",
    "price": 7000,
    "categorySlug": "geologie",
    "image": "/images/products/m243.jpg"
  },
  {
    "id": 852,
    "slug": "boite-de-roches-sedimentaires",
    "ref": "G003",
    "nameFr": "Boite de roches sédimentaires",
    "nameAr": "مجموعة صخور رسوبية",
    "price": 7000,
    "categorySlug": "geologie",
    "image": "/images/products/m240.jpg"
  },
  {
    "id": 856,
    "slug": "boite-de-roches-volcaniques-ou-ignees",
    "ref": "G004",
    "nameFr": "Boite de roches volcaniques ou ignées",
    "nameAr": "مجموعة صخور بركانية أونارية",
    "price": 7000,
    "categorySlug": "geologie",
    "image": "/images/products/m242.jpg"
  },
  {
    "id": 826,
    "slug": "coffret-de-42-specimens-de-mineraux-et-roches-42",
    "ref": "G005",
    "nameFr": "Coffret de 42 Spécimens de Minéraux et roches",
    "nameAr": "مجموعة من 42 نوع من المعادن و صخور",
    "price": 8500,
    "categorySlug": "geologie",
    "image": "/images/products/m030.jpg"
  },
  {
    "id": 823,
    "slug": "coffret-de-42-specimens-de-roches-42",
    "ref": "G006",
    "nameFr": "Coffret de 42 Spécimens de Roches",
    "nameAr": "مجموعة من 42 نوع من الصخور",
    "price": 8500,
    "categorySlug": "geologie",
    "image": "/images/products/m029.jpg"
  },
  {
    "id": 839,
    "slug": "coffret-specimens-de-sols",
    "ref": "G007",
    "nameFr": "Coffret Spécimens de Sols",
    "nameAr": "مجموعة أنواع من التربة",
    "price": 14500,
    "categorySlug": "geologie",
    "image": "/images/products/m031.jpg"
  },
  {
    "id": 836,
    "slug": "collection-de-10-fossiles-animalzoologique-10",
    "ref": "G008",
    "nameFr": "Collection de 10 fossiles animal(Zoologique)",
    "nameAr": "عينات من المستحاثات حيوانية 10",
    "price": 14500,
    "categorySlug": "geologie",
    "image": "/images/products/m069.jpg"
  },
  {
    "id": 833,
    "slug": "collection-de-10-fossiles-vegetal-botanique",
    "ref": "G009",
    "nameFr": "Collection de 10 fossiles végétal (Botanique)",
    "nameAr": "عينات من المستحاثات النباتية 10",
    "price": 14500,
    "categorySlug": "geologie",
    "image": "/images/products/m063.jpg"
  },
  {
    "id": 623,
    "slug": "collision-des-continents-disparition-des-oceans-et-formation-des-montagnes",
    "ref": "G010",
    "nameFr": "Collision des continents disparition des océans et formation des montagnes",
    "nameAr": "تصادم القارات اختفاء المحيطات و تشكل الجبال",
    "price": 17350,
    "categorySlug": "geologie",
    "image": "/images/products/M086-1.jpg"
  },
  {
    "id": 630,
    "slug": "travail-de-groupe-1-ere-am-science-physique",
    "ref": "G011",
    "nameFr": "Coupe d’un volcan",
    "nameAr": "مقطع لبركان",
    "price": 9950,
    "categorySlug": "geologie",
    "image": "/images/products/M0600.jpg"
  },
  {
    "id": 746,
    "slug": "phase-photochimique",
    "ref": "G012",
    "nameFr": "Coupe interne de la terre",
    "nameAr": "مقطع داخلي للأرض",
    "price": 12000,
    "categorySlug": "geologie",
    "image": "/images/products/M092.jpg"
  },
  {
    "id": 809,
    "slug": "dispositif-pour-letude-des-mouvements-des-plaque-terrestre",
    "ref": "G013",
    "nameFr": "Dispositif pour l’étude des mouvements des plaque terrestre",
    "nameAr": "جهاز لتوضيح الفوالق و الانزلقات",
    "price": 2950,
    "categorySlug": "geologie",
    "image": "/images/products/M045-1.jpg"
  },
  {
    "id": 165,
    "slug": "simulateur-dinjection-intramusculaire-de-fesses",
    "ref": "G014",
    "nameFr": "Formation des dorsales",
    "nameAr": "الظهرة و نشاطها",
    "price": 13500,
    "categorySlug": "geologie",
    "image": "/images/products/M062-1.jpg"
  },
  {
    "id": 162,
    "slug": "logiciel-scolaire",
    "ref": "G015",
    "nameFr": "Formation des plis et des failles",
    "nameAr": "تشكل الطيات و الفوالق",
    "price": 11000,
    "categorySlug": "geologie",
    "image": "/images/products/M061.jpg"
  },
  {
    "id": 2190,
    "slug": "acide-ribonucleique-arn",
    "ref": "B001",
    "nameFr": "Acide Ribonucléique ARN",
    "nameAr": "الحمض النووي الريبي",
    "price": 10500,
    "categorySlug": "science-de-la-vie-et-de-la-terre",
    "image": "/images/products/m140.jpg"
  },
  {
    "id": 2131,
    "slug": "appareil-genital-feminin-en-3-d",
    "ref": "B002",
    "nameFr": "Appareil génital féminin en 3 D",
    "nameAr": "الجهاز التناسلي عند المرأة بثلاث أبعاد",
    "price": 12000,
    "categorySlug": "science-de-la-vie-et-de-la-terre",
    "image": "/images/products/m024.jpg"
  },
  {
    "id": 2135,
    "slug": "appareil-genital-masculin-en-3d",
    "ref": "B003",
    "nameFr": "Appareil génital masculin en 3D",
    "nameAr": "الجهاز التناسلي عند الرجل بثلاث أبعاد",
    "price": 12000,
    "categorySlug": "science-de-la-vie-et-de-la-terre",
    "image": "/images/products/m025.jpg"
  },
  {
    "id": 982,
    "slug": "appareil-genital-masculin-et-feminin-plaque-magnetique",
    "ref": "B004",
    "nameFr": "Appareil génital masculin et féminin (PLAQUE MAGNETIQUE)",
    "nameAr": "الجهاز التناسلي الذكري و الانثوي (لوحة ممغنطة)",
    "price": 5600,
    "categorySlug": "science-de-la-vie-et-de-la-terre",
    "image": "/images/products/m341.jpg"
  },
  {
    "id": 2137,
    "slug": "appareil-urogenital-feminin",
    "ref": "B005",
    "nameFr": "Appareil urogénital féminin",
    "nameAr": "مجسم الجهاز البولي عند المرأة",
    "price": 7900,
    "categorySlug": "science-de-la-vie-et-de-la-terre",
    "image": "/images/products/m022.jpg"
  },
  {
    "id": 2139,
    "slug": "appareil-urogenital-masculin",
    "ref": "B006",
    "nameFr": "Appareil urogénital masculin",
    "nameAr": "مجسم الجهاز البولي عند الرجل",
    "price": 7900,
    "categorySlug": "science-de-la-vie-et-de-la-terre",
    "image": "/images/products/m023.jpg"
  },
  {
    "id": 2170,
    "slug": "caryotype-sur-tableau-magnetique",
    "ref": "B007",
    "nameFr": "Caryotype sur tableau magnétique",
    "nameAr": "طابع نووي على لوح مغناطيسي",
    "price": 14500,
    "categorySlug": "science-de-la-vie-et-de-la-terre",
    "image": "/images/products/m166.jpg"
  },
  {
    "id": 1740,
    "slug": "cellule-animal-et-vegetale-plaque-magnetique",
    "ref": "B008",
    "nameFr": "Cellule animal et végétale (PLAQUE MAGNETIQUE)",
    "nameAr": "الخلية الحيوانية و النباتية (لوحة ممغنطة)",
    "price": 5500,
    "categorySlug": "science-de-la-vie-et-de-la-terre",
    "image": "/images/products/m359.jpg"
  },
  {
    "id": 2150,
    "slug": "cellule-animale",
    "ref": "B009",
    "nameFr": "Cellule animale",
    "nameAr": "مجسم لمقطع لخلية حيوانية",
    "price": 11000,
    "categorySlug": "science-de-la-vie-et-de-la-terre",
    "image": "/images/products/m028.jpg"
  },
  {
    "id": 1623,
    "slug": "cellule-nerveuse-neurone-plaque-magnetique",
    "ref": "B010",
    "nameFr": "Cellule nerveuse (neurone) (PLAQUE MAGNETIQUE)",
    "nameAr": "الخلية العصبية(العصبون) (لوحة ممغنطة)",
    "price": 3250,
    "categorySlug": "science-de-la-vie-et-de-la-terre",
    "image": "/images/products/m300.jpg"
  },
  {
    "id": 1696,
    "slug": "cellule-phagocytairequatre-etapes-plaque-magnetique",
    "ref": "B011",
    "nameFr": "Cellule phagocytaire(Quatre étapes) (PLAQUE MAGNETIQUE)",
    "nameAr": "خلية بلعمية (أربع مراحل) (لوحة ممغنطة)",
    "price": 5600,
    "categorySlug": "science-de-la-vie-et-de-la-terre",
    "image": "/images/products/m306.jpg"
  },
  {
    "id": 2096,
    "slug": "cerveau-humain-en-8-parties-8",
    "ref": "B012",
    "nameFr": "Cerveau humain en 8 parties",
    "nameAr": "مجسم لمخ انسان بـ 8 أجزاء",
    "price": 7500,
    "categorySlug": "science-de-la-vie-et-de-la-terre",
    "image": "/images/products/m016.jpg"
  },
  {
    "id": 1525,
    "slug": "cerveau-humainplaque-magnetique",
    "ref": "B013",
    "nameFr": "Cerveau humain(PLAQUE MAGNETIQUE)",
    "nameAr": "دماغ الانسان(لوحة ممغنطة)",
    "price": 1950,
    "categorySlug": "science-de-la-vie-et-de-la-terre",
    "image": "/images/products/m299-1.jpg"
  },
  {
    "id": 1032,
    "slug": "chaines-alimentaire-dans-les-milieux-forestiers-et-aquatiquesplaque-magnetique",
    "ref": "B014",
    "nameFr": "Chaînes alimentaire dans les milieux forestiers et aquatiques(PLAQUE MAGNETIQUE)",
    "nameAr": "السلاسل الغذائية في الوسط الغابي و الوسط المائي (لوحة ممغنطة)",
    "price": 3200,
    "categorySlug": "science-de-la-vie-et-de-la-terre",
    "image": "/images/products/326-1.jpg"
  },
  {
    "id": 965,
    "slug": "cholesterol-sanguin-plaque-magnetique",
    "ref": "B015",
    "nameFr": "Cholestérol sanguin (PLAQUE MAGNETIQUE)",
    "nameAr": "الكوليستيرول في الدم (لوحة ممغنطة)",
    "price": 2100,
    "categorySlug": "science-de-la-vie-et-de-la-terre",
    "image": "/images/products/m338-1.jpg"
  },
  {
    "id": 880,
    "slug": "accessoire-pour-microscope",
    "ref": "O001",
    "nameFr": "Accessoire pour microscope",
    "nameAr": "لوازم المجهر",
    "price": 12000,
    "categorySlug": "materiels-dobservation",
    "image": "/images/products/p222-1-scaled.jpg"
  },
  {
    "id": 904,
    "slug": "camera-pour-microscope-1-3mp",
    "ref": "O002",
    "nameFr": "Caméra pour microscope 1.3MP",
    "nameAr": "كاميرا خاصة بالمجهر",
    "price": 8500,
    "categorySlug": "materiels-dobservation",
    "image": "/images/products/camera.jpg"
  },
  {
    "id": 907,
    "slug": "camera-pour-microscope-5-mp",
    "ref": "O003",
    "nameFr": "Caméra pour microscope 5 MP",
    "nameAr": "كاميرا خاصة بالمجهر",
    "price": 25000,
    "categorySlug": "materiels-dobservation",
    "image": "/images/products/camera.jpg"
  },
  {
    "id": 950,
    "slug": "coffret-de-100-preparations-microscopiques-la-botanique-100",
    "ref": "O004",
    "nameFr": "Coffret de 100 préparations microscopiques LA BOTANIQUE",
    "nameAr": "علبة 100 صفيحة مجهريه جاهزة للاستعمال علم النبتات",
    "price": 13500,
    "categorySlug": "materiels-dobservation",
    "image": "/images/products/m356.jpg"
  },
  {
    "id": 927,
    "slug": "coffret-de-100-preparations-microscopiques-melonges-100",
    "ref": "O005",
    "nameFr": "Coffret de 100 préparations microscopiques MELONGES",
    "nameAr": "علبة 100 صفيحة مجهريه جاهزة للاستعمال مختلطة",
    "price": 13500,
    "categorySlug": "materiels-dobservation",
    "image": "/images/products/m356.jpg"
  },
  {
    "id": 931,
    "slug": "coffret-de-100-preparations-microscopiques-zoology-100",
    "ref": "O006",
    "nameFr": "Coffret de 100 préparations microscopiques ZOOLOGY",
    "nameAr": "علبة 100 صفيحة مجهريه جاهزة للاستعمال علم الحيوان",
    "price": 13500,
    "categorySlug": "materiels-dobservation",
    "image": "/images/products/m356.jpg"
  },
  {
    "id": 921,
    "slug": "coffret-de-25-preparation-microscopique-lhistologie-et-la-physiologie-25",
    "ref": "O007",
    "nameFr": "Coffret de 25 préparation microscopique (l’histologie et la physiologie)",
    "nameAr": "علبة 25 صفيحة مجهريه جاهزة للاستعمال علم الأنسجة و الفسلجة",
    "price": 9000,
    "categorySlug": "materiels-dobservation",
    "image": "/images/products/M068.jpg"
  },
  {
    "id": 912,
    "slug": "coffret-de-25-preparations-microscopiques-25",
    "ref": "O008",
    "nameFr": "Coffret de 25 préparations microscopiques",
    "nameAr": "علبة 25 صفيحة مجهريه جاهزة للاستعمال علم النباتات",
    "price": 9000,
    "categorySlug": "materiels-dobservation",
    "image": "/images/products/M066.jpg"
  },
  {
    "id": 918,
    "slug": "coffret-de-25-preparations-microscopiques-25-2",
    "ref": "O009",
    "nameFr": "Coffret de 25 préparations microscopiques",
    "nameAr": "علبة 25 صفيحة مجهريه جاهزة للاستعمال علم الحيوانات",
    "price": 9000,
    "categorySlug": "materiels-dobservation",
    "image": "/images/products/M067.jpg"
  },
  {
    "id": 910,
    "slug": "huile-immersion-pour-microscope",
    "ref": "O010",
    "nameFr": "Huile immersion pour microscope",
    "nameAr": "زيت الغمر خاص بالمجهر",
    "price": 3250,
    "categorySlug": "materiels-dobservation",
    "image": "/images/products/C268.jpg"
  },
  {
    "id": 876,
    "slug": "kit-microscopecamera-usblogiciel-digiscope",
    "ref": "O011",
    "nameFr": "Kit microscope+Caméra USB+Logiciel (DIGISCOPE)",
    "nameAr": "طقم مجهر بكاميرة ديجيسكوب",
    "price": 74000,
    "categorySlug": "materiels-dobservation",
    "image": "/images/products/p394-1.jpg"
  },
  {
    "id": 885,
    "slug": "loupe-a-main",
    "ref": "O012",
    "nameFr": "Loupe à main",
    "nameAr": "عدسة يدوية",
    "price": 250,
    "categorySlug": "materiels-dobservation",
    "image": "/images/products/P010.jpg"
  },
  {
    "id": 883,
    "slug": "loupe-a-main-avec-eclairage",
    "ref": "O013",
    "nameFr": "Loupe à main avec éclairage",
    "nameAr": "لعدسة يدوية مضيئة",
    "price": 1500,
    "categorySlug": "materiels-dobservation",
    "image": "/images/products/p719.jpg"
  },
  {
    "id": 874,
    "slug": "loupe-binoculaire-eclairante-stereomicroscope",
    "ref": "O014",
    "nameFr": "Loupe binoculaire éclairante Steréomicroscope",
    "nameAr": "عدسة مكبرة مضيئة",
    "price": 48000,
    "categorySlug": "materiels-dobservation",
    "image": "/images/products/P129.jpg"
  },
  {
    "id": 871,
    "slug": "loupe-binoculaire-non-eclairante",
    "ref": "O015",
    "nameFr": "Loupe binoculaire non éclairante",
    "nameAr": "عدسة مكبرة غير مضيئة",
    "price": 34000,
    "categorySlug": "materiels-dobservation",
    "image": "/images/products/P128-2.jpg"
  },
  {
    "id": 4136,
    "slug": "accessoire-pour-flacons",
    "ref": "V001",
    "nameFr": "Accessoire pour flacons",
    "nameAr": "ملحق للقارورات",
    "price": 3300,
    "categorySlug": "verrerie-de-laboratoire",
    "image": "/images/products/V100.jpg"
  },
  {
    "id": 3905,
    "slug": "alcoometre",
    "ref": "V002",
    "nameFr": "Alcoomètre",
    "nameAr": "مقياس كحولي",
    "price": 4500,
    "categorySlug": "verrerie-de-laboratoire",
    "image": "/images/products/p688.jpg"
  },
  {
    "id": 3319,
    "slug": "ampoule-a-decanter-forme-poire-100-125ml",
    "ref": "V003",
    "nameFr": "Ampoule à décanter forme poire (100-125ml)",
    "nameAr": "قمع الفصل",
    "price": 4000,
    "categorySlug": "verrerie-de-laboratoire",
    "image": "/images/products/v172-2.jpg"
  },
  {
    "id": 3326,
    "slug": "ampoule-a-decanter-forme-poire-250ml",
    "ref": "V004",
    "nameFr": "Ampoule à décanter forme poire (250ml)",
    "nameAr": "قمع الفصل",
    "price": 4800,
    "categorySlug": "verrerie-de-laboratoire",
    "image": "/images/products/v172-2.jpg"
  },
  {
    "id": 3329,
    "slug": "ampoule-a-decanter-forme-poire-500ml",
    "ref": "V005",
    "nameFr": "Ampoule à décanter forme poire (500ml)",
    "nameAr": "قمع الفصل",
    "price": 5600,
    "categorySlug": "verrerie-de-laboratoire",
    "image": "/images/products/v172-2.jpg"
  },
  {
    "id": 3296,
    "slug": "ampoule-avec-robinet-forme-cylindrique-125ml",
    "ref": "V006",
    "nameFr": "Ampoule avec robinet forme cylindrique (125ml)",
    "nameAr": "قمع اسطواني بصنبور",
    "price": 4000,
    "categorySlug": "verrerie-de-laboratoire",
    "image": "/images/products/v140-3.jpg"
  },
  {
    "id": 3315,
    "slug": "ampoule-avec-robinet-forme-cylindrique-250ml",
    "ref": "V007",
    "nameFr": "Ampoule avec robinet forme cylindrique (250ml)",
    "nameAr": "قمع اسطواني بصنبور",
    "price": 4400,
    "categorySlug": "verrerie-de-laboratoire",
    "image": "/images/products/v140-3.jpg"
  },
  {
    "id": 3318,
    "slug": "ampoule-avec-robinet-forme-cylindrique-500ml",
    "ref": "V008",
    "nameFr": "Ampoule avec robinet forme cylindrique (500ml)",
    "nameAr": "قمع اسطواني بصنبور",
    "price": 5500,
    "categorySlug": "verrerie-de-laboratoire",
    "image": "/images/products/v140-3.jpg"
  },
  {
    "id": 3272,
    "slug": "anse-de-platine",
    "ref": "V009",
    "nameFr": "ANSE DE PLATINE",
    "nameAr": "مقبض بلاتيني",
    "price": 75,
    "categorySlug": "verrerie-de-laboratoire",
    "image": "/images/products/v362.jpg"
  },
  {
    "id": 3013,
    "slug": "ballon-en-verre-1000ml",
    "ref": "V010",
    "nameFr": "Ballon en verre (1000ml)",
    "nameAr": "حوجلات زجاجية",
    "price": 2500,
    "categorySlug": "verrerie-de-laboratoire",
    "image": "/images/products/v012-1.jpg"
  },
  {
    "id": 2996,
    "slug": "ballon-en-verre-100ml",
    "ref": "V011",
    "nameFr": "Ballon en verre (100ml)",
    "nameAr": "حوجلات زجاجية",
    "price": 950,
    "categorySlug": "verrerie-de-laboratoire",
    "image": "/images/products/v012-1.jpg"
  },
  {
    "id": 3005,
    "slug": "ballon-en-verre-250ml",
    "ref": "V012",
    "nameFr": "Ballon en verre (250ml)",
    "nameAr": "حوجلات زجاجية",
    "price": 1300,
    "categorySlug": "verrerie-de-laboratoire",
    "image": "/images/products/v012-1.jpg"
  },
  {
    "id": 3011,
    "slug": "ballon-en-verre-500ml",
    "ref": "V013",
    "nameFr": "Ballon en verre (500ml)",
    "nameAr": "حوجلات زجاجية",
    "price": 1500,
    "categorySlug": "verrerie-de-laboratoire",
    "image": "/images/products/v012-1.jpg"
  },
  {
    "id": 3407,
    "slug": "bec-bunsen-rechargeable",
    "ref": "V014",
    "nameFr": "Bec bunsen rechargeable",
    "nameAr": "موقد حراري",
    "price": 7500,
    "categorySlug": "verrerie-de-laboratoire",
    "image": "/images/products/v159-7.jpg"
  },
  {
    "id": 3402,
    "slug": "bec-bunsen",
    "ref": "V015",
    "nameFr": "Bec bunsen",
    "nameAr": "موقد حراري",
    "price": 4500,
    "categorySlug": "verrerie-de-laboratoire",
    "image": "/images/products/v077.jpg"
  },
  {
    "id": 2440,
    "slug": "monopoly",
    "ref": "A001",
    "nameFr": "(Monopoly)",
    "nameAr": "لعبة تربوية منوبولي عربي",
    "price": 2500,
    "categorySlug": "audio-visuel-et-animation-culturelle",
    "image": "/images/products/Jeux-de-societe-4.jpg"
  },
  {
    "id": 2441,
    "slug": "monopoly-2441",
    "ref": "A002",
    "nameFr": "(Monopoly)",
    "nameAr": "لعبة تربوية منوبولي فرنسي",
    "price": 2500,
    "categorySlug": "audio-visuel-et-animation-culturelle",
    "image": "/images/products/Jeux-de-societe-4.jpg"
  },
  {
    "id": 2699,
    "slug": "adaptateur-vga-hdmi",
    "ref": "A003",
    "nameFr": "Adaptateur VGA HDMI",
    "nameAr": "",
    "price": 1500,
    "categorySlug": "audio-visuel-et-animation-culturelle",
    "image": "/images/products/Yk197-1.jpg"
  },
  {
    "id": 2707,
    "slug": "adaptateur-vga-hdmi-2",
    "ref": "A004",
    "nameFr": "Adaptateur VGA HDMI",
    "nameAr": "",
    "price": 850,
    "categorySlug": "audio-visuel-et-animation-culturelle",
    "image": "/images/products/Yk197-1.jpg"
  },
  {
    "id": 2389,
    "slug": "amplificateur-de-sons-avec-cle-usb-professionnel-usb",
    "ref": "A005",
    "nameFr": "Amplificateur de sons avec clé USB PROFESSIONNEL USB",
    "nameAr": "جهاز لتكبير الصوت بمفتاح",
    "price": 55000,
    "categorySlug": "audio-visuel-et-animation-culturelle",
    "image": "/images/products/av044.jpg"
  },
  {
    "id": 2443,
    "slug": "back-gammon",
    "ref": "A006",
    "nameFr": "Back Gammon",
    "nameAr": "",
    "price": 1200,
    "categorySlug": "audio-visuel-et-animation-culturelle",
    "image": "/images/products/Jeux-de-societe-4.jpg"
  },
  {
    "id": 2786,
    "slug": "brosse-pour-tableau-blanc",
    "ref": "A007",
    "nameFr": "Brosse pour tableau blanc Monocouche",
    "nameAr": "ممسحة خاصة لسبورة بيضاء",
    "price": 100,
    "categorySlug": "audio-visuel-et-animation-culturelle",
    "image": "/images/products/av17b.jpg"
  },
  {
    "id": 2851,
    "slug": "brosse-pour-tableau-blanc-multicouche",
    "ref": "A008",
    "nameFr": "Brosse pour tableau blanc Multicouche",
    "nameAr": "ممسحة خاصة لسبورة بيضاء",
    "price": 150,
    "categorySlug": "audio-visuel-et-animation-culturelle",
    "image": "/images/products/av17b.jpg"
  },
  {
    "id": 2677,
    "slug": "cable-hdmi-1-5m",
    "ref": "A009",
    "nameFr": "Câble HDMI 1.5m",
    "nameAr": "",
    "price": 300,
    "categorySlug": "audio-visuel-et-animation-culturelle",
    "image": "/images/products/yk190.jpg"
  },
  {
    "id": 2693,
    "slug": "cable-hdmi-10m",
    "ref": "A010",
    "nameFr": "Câble HDMI 10m",
    "nameAr": "",
    "price": 1600,
    "categorySlug": "audio-visuel-et-animation-culturelle",
    "image": "/images/products/yk190-2.jpg"
  },
  {
    "id": 2697,
    "slug": "cable-hdmi-20m",
    "ref": "A011",
    "nameFr": "Câble HDMI 20m",
    "nameAr": "",
    "price": 3000,
    "categorySlug": "audio-visuel-et-animation-culturelle",
    "image": "/images/products/yk190-2.jpg"
  },
  {
    "id": 2685,
    "slug": "cable-hdmi-3m",
    "ref": "A012",
    "nameFr": "Câble HDMI 3m",
    "nameAr": "",
    "price": 500,
    "categorySlug": "audio-visuel-et-animation-culturelle",
    "image": "/images/products/yk190-2.jpg"
  },
  {
    "id": 2691,
    "slug": "cable-hdmi-5m",
    "ref": "A013",
    "nameFr": "Câble HDMI 5m",
    "nameAr": "",
    "price": 1000,
    "categorySlug": "audio-visuel-et-animation-culturelle",
    "image": "/images/products/yk190-2.jpg"
  },
  {
    "id": 2343,
    "slug": "cable-pour-installation-des-hauts-parleurs",
    "ref": "A014",
    "nameFr": "Câble pour installation des hauts parleurs",
    "nameAr": "كابل لتركيب مكبر الصوت",
    "price": 4950,
    "categorySlug": "audio-visuel-et-animation-culturelle",
    "image": "/images/products/av125.jpg"
  },
  {
    "id": 2353,
    "slug": "cable-pour-microphone-10m",
    "ref": "A015",
    "nameFr": "Câble pour microphone (10m)",
    "nameAr": "كابل خاص بالمودع",
    "price": 3500,
    "categorySlug": "audio-visuel-et-animation-culturelle",
    "image": "/images/products/av126-av127.jpg"
  },
  {
    "id": 1516,
    "slug": "geo-2",
    "ref": "M001",
    "nameFr": "",
    "nameAr": "خريطة آسيا اقتصاديا",
    "price": 3950,
    "categorySlug": "cartes-geographiques",
    "image": "/images/products/geo-2.jpg"
  },
  {
    "id": 1650,
    "slug": "geo-2-1650",
    "ref": "M002",
    "nameFr": "",
    "nameAr": "خريطة آسيا السكان",
    "price": 3950,
    "categorySlug": "cartes-geographiques",
    "image": "/images/products/geo-2.jpg"
  },
  {
    "id": 1657,
    "slug": "geo-2-1657",
    "ref": "M003",
    "nameFr": "",
    "nameAr": "خريطة آسيا المناخ",
    "price": 3950,
    "categorySlug": "cartes-geographiques",
    "image": "/images/products/geo-2.jpg"
  },
  {
    "id": 1635,
    "slug": "geo-2-1635",
    "ref": "M004",
    "nameFr": "",
    "nameAr": "خريطة آسيا الموقع الفلكي",
    "price": 3950,
    "categorySlug": "cartes-geographiques",
    "image": "/images/products/geo-2.jpg"
  },
  {
    "id": 1655,
    "slug": "geo-2-1655",
    "ref": "M005",
    "nameFr": "",
    "nameAr": "خريطة آسيا النبات",
    "price": 3950,
    "categorySlug": "cartes-geographiques",
    "image": "/images/products/geo-2.jpg"
  },
  {
    "id": 2068,
    "slug": "geo-2-2068",
    "ref": "M006",
    "nameFr": "",
    "nameAr": "خريطة آسيا صماء",
    "price": 3950,
    "categorySlug": "cartes-geographiques",
    "image": "/images/products/geo-2.jpg"
  },
  {
    "id": 1448,
    "slug": "geo-2-1448",
    "ref": "M007",
    "nameFr": "",
    "nameAr": "خريطة أبرز مظاهر السطح في الجزائر",
    "price": 3950,
    "categorySlug": "cartes-geographiques",
    "image": "/images/products/geo-2.jpg"
  },
  {
    "id": 1911,
    "slug": "geo-2-1911",
    "ref": "M008",
    "nameFr": "",
    "nameAr": "خريطة أروبا التساقط",
    "price": 3950,
    "categorySlug": "cartes-geographiques",
    "image": "/images/products/geo-2.jpg"
  },
  {
    "id": 1621,
    "slug": "geo-2-1621",
    "ref": "M009",
    "nameFr": "",
    "nameAr": "خريطة أصغر سبع دول مساحة في أوروبا",
    "price": 3950,
    "categorySlug": "cartes-geographiques",
    "image": "/images/products/geo-2.jpg"
  },
  {
    "id": 1677,
    "slug": "geo-2-1677",
    "ref": "M010",
    "nameFr": "",
    "nameAr": "خريطة أعنف الزلازل التي ضربت العالم",
    "price": 3950,
    "categorySlug": "cartes-geographiques",
    "image": "/images/products/geo-2.jpg"
  },
  {
    "id": 1445,
    "slug": "geo-2-1445",
    "ref": "M011",
    "nameFr": "",
    "nameAr": "خريطة أكبر البورصات في العالم",
    "price": 3950,
    "categorySlug": "cartes-geographiques",
    "image": "/images/products/geo-2.jpg"
  },
  {
    "id": 1807,
    "slug": "geo-2-1807",
    "ref": "M012",
    "nameFr": "",
    "nameAr": "خريطة أكبر عشر دول مصدرة و منتجة للحوم في العالم",
    "price": 3950,
    "categorySlug": "cartes-geographiques",
    "image": "/images/products/geo-2.jpg"
  },
  {
    "id": 1806,
    "slug": "geo-2-1806",
    "ref": "M013",
    "nameFr": "",
    "nameAr": "خريطة أكبر عشر دول منتجة للصوف في العالم",
    "price": 3950,
    "categorySlug": "cartes-geographiques",
    "image": "/images/products/geo-2.jpg"
  },
  {
    "id": 2002,
    "slug": "geo-2-2002",
    "ref": "M014",
    "nameFr": "",
    "nameAr": "خريطة أكثر الدول المستفيدة من مشروع مارشال",
    "price": 3950,
    "categorySlug": "cartes-geographiques",
    "image": "/images/products/geo-2.jpg"
  },
  {
    "id": 1560,
    "slug": "geo-2-1560",
    "ref": "M015",
    "nameFr": "",
    "nameAr": "خريطة أمريكا الجنوبية النبات",
    "price": 3950,
    "categorySlug": "cartes-geographiques",
    "image": "/images/products/geo-2.jpg"
  },
  {
    "id": 1207,
    "slug": "acetaldhyde",
    "ref": "P001",
    "nameFr": "Acetaldhyde (60ml)",
    "nameAr": "أسيتلدهيد",
    "price": 2700,
    "categorySlug": "produits-chimiques",
    "image": "/images/products/PRODUIT-CHIMIQUE.jpg"
  },
  {
    "id": 1209,
    "slug": "acetate-dammonium",
    "ref": "P002",
    "nameFr": "Acetate D’ammonium (25g)",
    "nameAr": "خلات الأمونيوم",
    "price": 1300,
    "categorySlug": "produits-chimiques",
    "image": "/images/products/PRODUIT-CHIMIQUE.jpg"
  },
  {
    "id": 1222,
    "slug": "acetone",
    "ref": "P003",
    "nameFr": "Acetone (250ml)",
    "nameAr": "الأسيتون",
    "price": 1300,
    "categorySlug": "produits-chimiques",
    "image": "/images/products/PRODUIT-CHIMIQUE.jpg"
  },
  {
    "id": 1225,
    "slug": "acide-acetique-a-8",
    "ref": "P004",
    "nameFr": "Acide Acetique A 8% (250ml)",
    "nameAr": "حمض الخل",
    "price": 550,
    "categorySlug": "produits-chimiques",
    "image": "/images/products/PRODUIT-CHIMIQUE.jpg"
  },
  {
    "id": 1236,
    "slug": "acide-acetique-glacial-100-250ml",
    "ref": "P005",
    "nameFr": "Acide Acetique GLACIAL 100% (250ml)",
    "nameAr": "حمض الخل",
    "price": 850,
    "categorySlug": "produits-chimiques",
    "image": "/images/products/PRODUIT-CHIMIQUE.jpg"
  },
  {
    "id": 1250,
    "slug": "acide-borique-100g",
    "ref": "P006",
    "nameFr": "Acide Borique (100g)",
    "nameAr": "حمض البوريك",
    "price": 1300,
    "categorySlug": "produits-chimiques",
    "image": "/images/products/PRODUIT-CHIMIQUE.jpg"
  },
  {
    "id": 1255,
    "slug": "acide-chlorhydrique-250ml",
    "ref": "P007",
    "nameFr": "Acide Chlorhydrique (250ml)",
    "nameAr": "حمض الكور الماء",
    "price": 1000,
    "categorySlug": "produits-chimiques",
    "image": "/images/products/PRODUIT-CHIMIQUE.jpg"
  },
  {
    "id": 1262,
    "slug": "acide-citrique-100g",
    "ref": "P008",
    "nameFr": "Acide Citrique (100g)",
    "nameAr": "حامض الستريك",
    "price": 550,
    "categorySlug": "produits-chimiques",
    "image": "/images/products/PRODUIT-CHIMIQUE.jpg"
  },
  {
    "id": 1266,
    "slug": "acide-formique-125ml",
    "ref": "P009",
    "nameFr": "Acide Formique (125ml)",
    "nameAr": "حمض النمل",
    "price": 1400,
    "categorySlug": "produits-chimiques",
    "image": "/images/products/PRODUIT-CHIMIQUE.jpg"
  },
  {
    "id": 1271,
    "slug": "acide-nitrique-250ml",
    "ref": "P010",
    "nameFr": "Acide Nitrique (250ml)",
    "nameAr": "حمض الأزوت",
    "price": 1300,
    "categorySlug": "produits-chimiques",
    "image": "/images/products/PRODUIT-CHIMIQUE.jpg"
  },
  {
    "id": 1292,
    "slug": "acide-orthophosphorique-125ml",
    "ref": "P011",
    "nameFr": "Acide Orthophosphorique (125ml)",
    "nameAr": "حمض الفوسفوريك",
    "price": 1750,
    "categorySlug": "produits-chimiques",
    "image": "/images/products/PRODUIT-CHIMIQUE.jpg"
  },
  {
    "id": 1296,
    "slug": "acide-oxalique-100g",
    "ref": "P012",
    "nameFr": "Acide Oxalique (100g)",
    "nameAr": "حمض الأكساليك",
    "price": 1000,
    "categorySlug": "produits-chimiques",
    "image": "/images/products/PRODUIT-CHIMIQUE.jpg"
  },
  {
    "id": 1308,
    "slug": "acide-picrique-125ml",
    "ref": "P013",
    "nameFr": "Acide Picrique (125ml)",
    "nameAr": "حمض البكريك",
    "price": 1400,
    "categorySlug": "produits-chimiques",
    "image": "/images/products/PRODUIT-CHIMIQUE.jpg"
  },
  {
    "id": 4372,
    "slug": "acide-salicylique-50g",
    "ref": "P014",
    "nameFr": "Acide Salicylique 50g",
    "nameAr": "حمض السلسليك",
    "price": 1100,
    "categorySlug": "produits-chimiques",
    "image": "/images/products/PRODUIT-CHIMIQUE.jpg"
  },
  {
    "id": 1318,
    "slug": "acide-sulfurique250ml",
    "ref": "P015",
    "nameFr": "Acide Sulfurique(250ml)",
    "nameAr": "حمض الكبريت",
    "price": 1100,
    "categorySlug": "produits-chimiques",
    "image": "/images/products/PRODUIT-CHIMIQUE.jpg"
  },
  {
    "id": 2880,
    "slug": "chassis-de-voiture-intelligente-encodeur-de-bande-4x4-robot-intelligent-fa6003",
    "ref": "E001",
    "nameFr": "Châssis de voiture intelligente (encodeur de bande 4×4 robot intelligent FA6003)",
    "nameAr": "هيكل السيارة الذكية (جهاز تشفير الشريط الذكي للروبوت 4×4)",
    "price": 4000,
    "categorySlug": "arduino-et-electronique",
    "image": "/images/products/ADR002.jpg"
  },
  {
    "id": 2844,
    "slug": "ADR004",
    "ref": "E002",
    "nameFr": "Châssis de voiture intelligente (encodeur de bande, robot 4×4 intelligent – FA6003)",
    "nameAr": "هيكل السيارة الذكية (مشفر الشريط، روبوت ذكي رباعي الدفع)",
    "price": 4000,
    "categorySlug": "arduino-et-electronique",
    "image": "/images/products/ADR004.jpg"
  },
  {
    "id": 2883,
    "slug": "lcr-metre-lcr",
    "ref": "E003",
    "nameFr": "Adaptateur BNC -Banane",
    "nameAr": "",
    "price": 1000,
    "categorySlug": "arduino-et-electronique",
    "image": "/images/products/p395.jpg"
  },
  {
    "id": 2277,
    "slug": "boite-densemble-pour-montage-electronique",
    "ref": "E004",
    "nameFr": "Boite d’ensemble pour montage électronique",
    "nameAr": "مجموعة تركيبات الكترونية",
    "price": 4500,
    "categorySlug": "arduino-et-electronique",
    "image": "/images/products/ELN15-1.jpg"
  },
  {
    "id": 2333,
    "slug": "boite-de-100-fusibles",
    "ref": "E005",
    "nameFr": "Boite de 100 fusibles",
    "nameAr": "",
    "price": 7500,
    "categorySlug": "arduino-et-electronique",
    "image": "/images/products/ELN102.jpg"
  },
  {
    "id": 2326,
    "slug": "cable-bnc-avec-2-fiches-banane",
    "ref": "E006",
    "nameFr": "Câble BNC avec 2 fiches banane",
    "nameAr": "",
    "price": 1900,
    "categorySlug": "arduino-et-electronique",
    "image": "/images/products/ELN98.jpg"
  },
  {
    "id": 2321,
    "slug": "cable-bnc-avec-pince-crocodile",
    "ref": "E007",
    "nameFr": "Câble BNC avec pince crocodile",
    "nameAr": "",
    "price": 1600,
    "categorySlug": "arduino-et-electronique",
    "image": "/images/products/ELN97.jpg"
  },
  {
    "id": 2306,
    "slug": "cable-bnc-mal-mal-pour-gbf-et-oscilloscope",
    "ref": "E008",
    "nameFr": "Câble BNC mal-mal pour GBF et oscilloscope",
    "nameAr": "",
    "price": 1700,
    "categorySlug": "arduino-et-electronique",
    "image": "/images/products/ELN96.jpg"
  },
  {
    "id": 2623,
    "slug": "circuit-4017be-10-lot",
    "ref": "E009",
    "nameFr": "Circuit 4017BE 10 LOT",
    "nameAr": "",
    "price": 2000,
    "categorySlug": "arduino-et-electronique",
    "image": "/images/products/CIRCUIT-1.jpg"
  },
  {
    "id": 2614,
    "slug": "circuit-atmga329p-dip28-10-lot",
    "ref": "E010",
    "nameFr": "Circuit Atmga329p-DIP28 10 LOT",
    "nameAr": "",
    "price": 5200,
    "categorySlug": "arduino-et-electronique",
    "image": "/images/products/CIRCUIT-1.jpg"
  },
  {
    "id": 2690,
    "slug": "circuit-ne555p-10-lot",
    "ref": "E011",
    "nameFr": "Circuit NE555P 10 LOT",
    "nameAr": "",
    "price": 2000,
    "categorySlug": "arduino-et-electronique",
    "image": "/images/products/CIRCUIT-1.jpg"
  },
  {
    "id": 2554,
    "slug": "circuit-integre-cd4011be-10-lot",
    "ref": "E012",
    "nameFr": "Circuit intégré CD4011BE 10 LOT",
    "nameAr": "",
    "price": 2500,
    "categorySlug": "arduino-et-electronique",
    "image": "/images/products/CIRCUIT-INTEGRE.jpg"
  },
  {
    "id": 2564,
    "slug": "circuit-integre-cd4028be-10-lot",
    "ref": "E013",
    "nameFr": "Circuit intégré CD4028BE 10 LOT",
    "nameAr": "",
    "price": 3000,
    "categorySlug": "arduino-et-electronique",
    "image": "/images/products/CIRCUIT-INTEGRE.jpg"
  },
  {
    "id": 2566,
    "slug": "circuit-integre-cd4030be-10-lot",
    "ref": "E014",
    "nameFr": "Circuit intégré CD4030BE 10 LOT",
    "nameAr": "",
    "price": 4000,
    "categorySlug": "arduino-et-electronique",
    "image": "/images/products/CIRCUIT-INTEGRE.jpg"
  },
  {
    "id": 2573,
    "slug": "circuit-integre-cd4069be-10-lot",
    "ref": "E015",
    "nameFr": "Circuit intégré CD4069BE 10 LOT",
    "nameAr": "",
    "price": 2000,
    "categorySlug": "arduino-et-electronique",
    "image": "/images/products/CIRCUIT-INTEGRE.jpg"
  }
]
