/**
 * Copy for the control panel.
 *
 * The panel is a staff-only tool, so its strings live in this self-contained
 * dictionary rather than in the storefront's `src/i18n/translations.ts`. That
 * keeps the public site's dictionary focused on customer-facing copy while the
 * panel still supports both languages. French is the reference language here,
 * matching the back-office language used on the source site.
 */
import type { Language } from '../../data/types'

/** French copy — the reference dictionary; every other language must match it. */
const fr = {
  'panel.brand': 'Panneau de gestion',
  'panel.brandSub': 'Administration du site',
  'panel.viewSite': 'Voir le site',
  'panel.logout': 'Déconnexion',
  'panel.menu': 'Menu',
  'ui.loading': 'Chargement…',
  'ui.save': 'Enregistrer',
  'ui.saving': 'Enregistrement…',
  'ui.cancel': 'Annuler',
  'ui.delete': 'Supprimer',
  'ui.deleting': 'Suppression…',
  'ui.edit': 'Modifier',
  'ui.add': 'Ajouter',
  'ui.search': 'Rechercher',
  'ui.refresh': 'Actualiser',
  'ui.close': 'Fermer',
  'ui.confirm': 'Confirmer',
  'ui.preview': 'Aperçu',
  'ui.checkAll': 'Tout',
  'ui.page': 'Page',
  'ui.previous': 'Précédent',
  'ui.next': 'Suivant',
  'ui.of': 'sur',
  'ui.optional': 'facultatif',
  'ui.error': 'Une erreur est survenue. Vérifiez que le serveur est démarré.',
  'ui.copied': 'Copié',
  'login.title': 'Connexion au panneau',
  'login.subtitle': 'Entrez le mot de passe administrateur pour continuer.',
  'login.password': 'Mot de passe',
  'login.submit': 'Se connecter',
  'login.submitting': 'Connexion…',
  'login.error': 'Mot de passe incorrect.',
  'login.unreachable':
    'Serveur injoignable. Lancez « npm run server » (ou « npm run dev:all »), puis réessayez.',
  'login.defaultHint':
    "Aucun mot de passe n'est configuré côté serveur : la valeur de développement « admin123 » est utilisée. Définissez ADMIN_PASSWORD avant la mise en ligne.",
  'login.back': 'Retour au site',
  'nav.dashboard': 'Tableau de bord',
  'nav.products': 'Produits',
  'nav.categories': 'Catégories',
  'nav.orders': 'Commandes',
  'nav.settings': 'Paramètres',
  'dash.title': 'Tableau de bord',
  'dash.subtitle': 'Vue d’ensemble de votre catalogue et de vos commandes.',
  'dash.products': 'Produits',
  'dash.categories': 'Catégories',
  'dash.orders': 'Commandes reçues',
  'dash.pending': 'À confirmer',
  'dash.value': 'Valeur du catalogue',
  'dash.sales': 'Ventes (commandes livrées)',
  'dash.salesCount': 'commande(s) livrée(s)',
  'dash.recent': 'Dernières commandes',
  'dash.noOrders': 'Aucune commande pour le moment.',
  'dash.shortcuts': 'Raccourcis',
  'dash.addProduct': 'Ajouter un produit',
  'dash.manageOrders': 'Traiter les commandes',
  'dash.editSite': 'Modifier les coordonnées',
  'dash.lastUpdate': 'Dernière mise à jour',
  'dash.topCategories': 'Répartition par catégorie',
  'products.title': 'Produits',
  'products.subtitle': 'Ajoutez, modifiez ou supprimez les articles du catalogue.',
  'products.new': 'Nouveau produit',
  'products.edit': 'Modifier le produit',
  'products.search': 'Rechercher par nom ou référence',
  'products.allCategories': 'Toutes les catégories',
  'products.thumb': 'Image',
  'products.ref': 'Référence',
  'products.nameFr': 'Nom (FR)',
  'products.nameAr': 'Nom (AR)',
  'products.price': 'Prix (DA)',
  'products.category': 'Catégorie',
  'products.empty': 'Aucun produit ne correspond.',
  'products.count': 'produit(s)',
  'products.imageUrl': "URL de l'image",
  'products.upload': 'Téléverser une image',
  'products.uploading': 'Téléversement…',
  'products.uploaded': 'Image téléversée avec succès.',
  'products.uploadFailed': 'Échec du téléversement de l’image.',
  'products.badType':
    'Format non pris en charge. Choisissez une image JPG, PNG, WEBP, GIF, SVG, AVIF ou BMP, ou un PDF.',
  'products.tooLarge': 'Fichier trop volumineux : 16 Mo maximum.',
  'products.sessionExpired':
    'Session expirée : déconnectez-vous puis reconnectez-vous avant de téléverser un fichier.',
  'products.previewFailed':
    'Image introuvable : le chemin est incorrect ou le fichier n’est pas accessible.',
  'products.imageHint': 'JPG, PNG, WEBP, GIF, SVG ou PDF — 16 Mo maximum.',
  'products.slug': 'Identifiant URL (slug)',
  'products.slugHint': 'Laisser vide pour générer depuis le nom.',
  'products.refPlaceholder': 'Ex : GEO-04',
  'products.deleteConfirm': 'Supprimer définitivement ce produit ?',
  'products.savedNew': 'Produit ajouté.',
  'products.savedEdit': 'Produit mis à jour.',
  'products.deleted': 'Produit supprimé.',
  'products.selectCategory': 'Choisir une catégorie',
  'cats.title': 'Catégories',
  'cats.subtitle': 'Organisez le catalogue ; chaque catégorie devient une page du site.',
  'cats.new': 'Nouvelle catégorie',
  'cats.edit': 'Modifier la catégorie',
  'cats.name': 'Nom',
  'cats.count': 'Nombre de produits',
  'cats.image': 'Image',
  'cats.empty': 'Aucune catégorie.',
  'cats.deleteConfirm': 'Supprimer cette catégorie ? Ses produits seront conservés.',
  'cats.savedNew': 'Catégorie ajoutée.',
  'cats.savedEdit': 'Catégorie mise à jour.',
  'cats.deleted': 'Catégorie supprimée.',
  'cats.products': 'produits',
  'orders.title': 'Commandes',
  'orders.subtitle':
    'Appelez le client pour confirmer, puis mettez à jour le statut. Paiement à la livraison.',
  'orders.empty': 'Aucune commande pour ce filtre.',
  'orders.number': 'N°',
  'orders.date': 'Date',
  'orders.customer': 'Client',
  'orders.phone': 'Téléphone',
  'orders.items': 'Articles',
  'orders.total': 'Montant',
  'orders.status': 'Statut',
  'orders.detail': 'Détail de la commande',
  'orders.callCustomer': 'Appeler le client',
  'orders.copyPhone': 'Copier le numéro',
  'orders.wilaya': 'Wilaya',
  'orders.commune': 'Commune',
  'orders.address': 'Adresse',
  'orders.notes': 'Remarques',
  'orders.noNotes': 'Aucune remarque.',
  'orders.language': 'Langue du client',
  'orders.subtotal': 'Sous-total',
  'orders.payOnDelivery': 'Paiement à la livraison',
  'orders.statusUpdated': 'Statut mis à jour.',
  'orders.deleteConfirm': 'Supprimer définitivement cette commande ?',
  'orders.deleted': 'Commande supprimée.',
  'orders.status.pending': 'À confirmer',
  'orders.status.confirmed': 'Confirmée',
  'orders.status.delivered': 'Livrée',
  'orders.status.cancelled': 'Annulée',
  'orders.filter.all': 'Toutes',
  'set.title': 'Paramètres du site',
  'set.subtitle': 'Coordonnées, réseaux sociaux, images et catalogues téléchargeables.',
  'set.contact': 'Coordonnées',
  'set.topPhones': 'Téléphones (bandeau haut)',
  'set.phoneLines': 'Lignes téléphoniques (page contact)',
  'set.deliveryPhone': 'Numéro livraison',
  'set.availabilityPhone': 'Numéro de disponibilité',
  'set.fax': 'Fax',
  'set.email': 'Email',
  'set.address': 'Adresse',
  'set.address1': 'Adresse — ligne 1',
  'set.address2': 'Adresse — ligne 2',
  'set.address3': 'Adresse — ligne 3',
  'set.orderForm': 'Bon de commande (PDF)',
  'set.socials': 'Réseaux sociaux',
  'set.socialUrl': 'Lien',
  'set.images': 'Images du site',
  'set.imageHero': "Image d'accueil (hero)",
  'set.imageWhyUs': 'Image « Qui sommes-nous »',
  'set.imageLogo': 'Logo',
  'set.catalogues': 'Catalogues téléchargeables',
  'set.catalogueTitleFr': 'Titre (FR)',
  'set.catalogueTitleAr': 'Titre (AR)',
  'set.catalogueCover': 'Couverture',
  'set.catalogueFile': 'Fichier PDF',
  'set.addCatalogue': 'Ajouter un catalogue',
  'set.removeCatalogue': 'Retirer',
  'set.saved': 'Paramètres enregistrés.',
  'set.addRow': 'Ajouter une ligne',
  'set.removeRow': 'Retirer la ligne',
} as const

/** Every key the panel uses. */
export type AdminTextKey = keyof typeof fr

/** Arabic mirror — must define exactly the same keys as `fr`. */
const ar: Record<AdminTextKey, string> = {
  'panel.brand': 'لوحة التحكم',
  'panel.brandSub': 'إدارة الموقع',
  'panel.viewSite': 'عرض الموقع',
  'panel.logout': 'تسجيل الخروج',
  'panel.menu': 'القائمة',
  'ui.loading': 'جارٍ التحميل…',
  'ui.save': 'حفظ',
  'ui.saving': 'جارٍ الحفظ…',
  'ui.cancel': 'إلغاء',
  'ui.delete': 'حذف',
  'ui.deleting': 'جارٍ الحذف…',
  'ui.edit': 'تعديل',
  'ui.add': 'إضافة',
  'ui.search': 'بحث',
  'ui.refresh': 'تحديث',
  'ui.close': 'إغلاق',
  'ui.confirm': 'تأكيد',
  'ui.preview': 'معاينة',
  'ui.checkAll': 'الكل',
  'ui.page': 'صفحة',
  'ui.previous': 'السابق',
  'ui.next': 'التالي',
  'ui.of': 'من',
  'ui.optional': 'اختياري',
  'ui.error': 'حدث خطأ. تأكد من تشغيل الخادم.',
  'ui.copied': 'تم النسخ',
  'login.title': 'الدخول إلى لوحة التحكم',
  'login.subtitle': 'أدخل كلمة مرور الإدارة للمتابعة.',
  'login.password': 'كلمة المرور',
  'login.submit': 'دخول',
  'login.submitting': 'جارٍ الدخول…',
  'login.error': 'كلمة المرور غير صحيحة.',
  'login.unreachable': 'تعذّر الوصول إلى الخادم. شغّل الأمر « npm run server » ثم أعد المحاولة.',
  'login.defaultHint':
    'لم تُضبط كلمة مرور على الخادم، لذلك تُستعمل القيمة التطويرية « admin123 ». اضبط ADMIN_PASSWORD قبل النشر.',
  'login.back': 'العودة إلى الموقع',
  'nav.dashboard': 'لوحة المعلومات',
  'nav.products': 'المنتجات',
  'nav.categories': 'الفئات',
  'nav.orders': 'الطلبات',
  'nav.settings': 'الإعدادات',
  'dash.title': 'لوحة المعلومات',
  'dash.subtitle': 'نظرة شاملة على الكتالوج والطلبات.',
  'dash.products': 'المنتجات',
  'dash.categories': 'الفئات',
  'dash.orders': 'الطلبات المستلمة',
  'dash.pending': 'في انتظار التأكيد',
  'dash.value': 'قيمة الكتالوج',
  'dash.sales': 'المبيعات (الطلبات المسلّمة)',
  'dash.salesCount': 'طلب مُسلَّم',
  'dash.recent': 'أحدث الطلبات',
  'dash.noOrders': 'لا توجد طلبات حالياً.',
  'dash.shortcuts': 'اختصارات',
  'dash.addProduct': 'إضافة منتج',
  'dash.manageOrders': 'معالجة الطلبات',
  'dash.editSite': 'تعديل معلومات الاتصال',
  'dash.lastUpdate': 'آخر تحديث',
  'dash.topCategories': 'التوزيع حسب الفئة',
  'products.title': 'المنتجات',
  'products.subtitle': 'أضف أو عدّل أو احذف منتجات الكتالوج.',
  'products.new': 'منتج جديد',
  'products.edit': 'تعديل المنتج',
  'products.search': 'ابحث بالاسم أو المرجع',
  'products.allCategories': 'كل الفئات',
  'products.thumb': 'الصورة',
  'products.ref': 'المرجع',
  'products.nameFr': 'الاسم (بالفرنسية)',
  'products.nameAr': 'الاسم (بالعربية)',
  'products.price': 'السعر (د.ج)',
  'products.category': 'الفئة',
  'products.empty': 'لا يوجد منتج مطابق.',
  'products.count': 'منتج',
  'products.imageUrl': 'رابط الصورة',
  'products.upload': 'رفع صورة',
  'products.uploading': 'جارٍ الرفع…',
  'products.uploaded': 'تم رفع الصورة بنجاح.',
  'products.uploadFailed': 'فشل رفع الصورة.',
  'products.badType':
    'صيغة غير مدعومة. اختر صورة JPG أو PNG أو WEBP أو GIF أو SVG أو AVIF أو BMP، أو ملف PDF.',
  'products.tooLarge': 'الملف كبير جداً: الحد الأقصى 16 ميغابايت.',
  'products.sessionExpired':
    'انتهت الجلسة: سجّلوا الخروج ثم الدخول مجدداً قبل رفع الملف.',
  'products.previewFailed': 'الصورة غير موجودة: المسار غير صحيح أو الملف غير متاح.',
  'products.imageHint': 'JPG أو PNG أو WEBP أو GIF أو SVG أو PDF — 16 ميغابايت كحد أقصى.',
  'products.slug': 'المعرّف في الرابط (slug)',
  'products.slugHint': 'اتركه فارغاً ليُنشأ من الاسم.',
  'products.refPlaceholder': 'مثال: GEO-04',
  'products.deleteConfirm': 'حذف هذا المنتج نهائياً؟',
  'products.savedNew': 'تمت إضافة المنتج.',
  'products.savedEdit': 'تم تحديث المنتج.',
  'products.deleted': 'تم حذف المنتج.',
  'products.selectCategory': 'اختر فئة',
  'cats.title': 'الفئات',
  'cats.subtitle': 'نظّم الكتالوج؛ كل فئة تصبح صفحة في الموقع.',
  'cats.new': 'فئة جديدة',
  'cats.edit': 'تعديل الفئة',
  'cats.name': 'الاسم',
  'cats.count': 'عدد المنتجات',
  'cats.image': 'الصورة',
  'cats.empty': 'لا توجد فئات.',
  'cats.deleteConfirm': 'حذف هذه الفئة؟ ستبقى منتجاتها محفوظة.',
  'cats.savedNew': 'تمت إضافة الفئة.',
  'cats.savedEdit': 'تم تحديث الفئة.',
  'cats.deleted': 'تم حذف الفئة.',
  'cats.products': 'منتج',
  'orders.title': 'الطلبات',
  'orders.subtitle': 'اتصل بالعميل للتأكيد ثم حدّث الحالة. الدفع عند التسليم.',
  'orders.empty': 'لا توجد طلبات في هذا التصنيف.',
  'orders.number': 'الرقم',
  'orders.date': 'التاريخ',
  'orders.customer': 'العميل',
  'orders.phone': 'الهاتف',
  'orders.items': 'المنتجات',
  'orders.total': 'المبلغ',
  'orders.status': 'الحالة',
  'orders.detail': 'تفاصيل الطلب',
  'orders.callCustomer': 'الاتصال بالعميل',
  'orders.copyPhone': 'نسخ الرقم',
  'orders.wilaya': 'الولاية',
  'orders.commune': 'البلدية',
  'orders.address': 'العنوان',
  'orders.notes': 'ملاحظات',
  'orders.noNotes': 'لا توجد ملاحظات.',
  'orders.language': 'لغة العميل',
  'orders.subtotal': 'المجموع الفرعي',
  'orders.payOnDelivery': 'الدفع عند التسليم',
  'orders.statusUpdated': 'تم تحديث الحالة.',
  'orders.deleteConfirm': 'حذف هذا الطلب نهائياً؟',
  'orders.deleted': 'تم حذف الطلب.',
  'orders.status.pending': 'في انتظار التأكيد',
  'orders.status.confirmed': 'مؤكد',
  'orders.status.delivered': 'تم التسليم',
  'orders.status.cancelled': 'ملغى',
  'orders.filter.all': 'الكل',
  'set.title': 'إعدادات الموقع',
  'set.subtitle': 'معلومات الاتصال، الشبكات الاجتماعية، الصور والكتالوجات.',
  'set.contact': 'معلومات الاتصال',
  'set.topPhones': 'أرقام الهاتف (الشريط العلوي)',
  'set.phoneLines': 'أرقام الهاتف (صفحة الاتصال)',
  'set.deliveryPhone': 'رقم التوصيل',
  'set.availabilityPhone': 'رقم الاستفسار عن التوفر',
  'set.fax': 'الفاكس',
  'set.email': 'البريد الإلكتروني',
  'set.address': 'العنوان',
  'set.address1': 'العنوان — السطر 1',
  'set.address2': 'العنوان — السطر 2',
  'set.address3': 'العنوان — السطر 3',
  'set.orderForm': 'طلب الشراء (PDF)',
  'set.socials': 'الشبكات الاجتماعية',
  'set.socialUrl': 'الرابط',
  'set.images': 'صور الموقع',
  'set.imageHero': 'صورة الواجهة الرئيسية',
  'set.imageWhyUs': 'صورة «من نحن»',
  'set.imageLogo': 'الشعار',
  'set.catalogues': 'الكتالوجات للتحميل',
  'set.catalogueTitleFr': 'العنوان (فرنسية)',
  'set.catalogueTitleAr': 'العنوان (عربية)',
  'set.catalogueCover': 'الغلاف',
  'set.catalogueFile': 'ملف PDF',
  'set.addCatalogue': 'إضافة كتالوج',
  'set.removeCatalogue': 'حذف',
  'set.saved': 'تم حفظ الإعدادات.',
  'set.addRow': 'إضافة سطر',
  'set.removeRow': 'حذف السطر',
}

/** The panel dictionaries, keyed by language. */
export const adminText: Record<Language, Record<AdminTextKey, string>> = { fr, ar }